version: "3"

services:
  client:
    depends_on:
      - donation-service
    image: client:1.0
    build: ./front-end
    ports:
      - "8080:8080"
    environment: 
      - DONATION_ENDPOINT=http://donation-service:3000/
  donation-service:
    image: donation:1.0
    build: ./donation-service
    ports:
      - "3000:3000"
