version: "3"

services:
  api:
    depends_on: 
      - user
      
    image: api:1.0
    build: ./api
    ports:
      - "3000:3000"
    environment: 
      - USER_SERVICE_ENDPOINT=http://user:3000/
      
  user: 
    image: user:1.0
    build: ./user-service
    ports: 
      - "3050:3000"
  
  client:
    depends_on:
      - api
    image: client:1.0
    build: ./front-end
    ports:
      - "8080:8080"
    environment: 
      - API_ENDPOINT=http://api:3000/
